# DannyEco config

# The following options configure the sell limits.
sell-limits:
  # How frequently sell limits are diminished in ticks.
  # The default is 1 hour (20tps * 60s * 60m)
  reset-delay-ticks: 72000

  # Do you want the sell limits being reset to be announced?
  # If this is false (default), only console will receive the announce-message below.
  # If this is true, it overrides tell-console-limits-reset and the message will be
  # shown to all players and console.
  announce-limits-reset: false
  # Message console when they are reset?
  tell-console-limits-reset: true
  # Announcement message
  # Colors and formatting can be specified with '&' codes.
  announce-message: "&d[DannyEco] &7Sell limits have been refreshed!"

# Regarding economy analysis (volume tracking, etc.)
eco-analytics:
  # If this is false, the entire feature will be unavailable on the server.
  # There is no real downside to leaving this enabled- the storage used by
  # this feature is minimal.
  enabled: true

# Should a log that tracks who sells what on the server be maintained?
logging:
  # If false, sale logs will not be available
  enabled: true
  # If false, logs will not be saved to disk.
  persist-logs: true

# DO NOT TOUCH THIS!
$version: 3